  name: Check TikTok Live

  on:
    schedule:
      - cron: '*/5 * * * *'  # Runs every 5 minutes

  jobs:
    check-tiktok-live:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Trigger Vercel function
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: |
          curl -X GET https://$VERCEL_URL/live